config/routes.rb
Rails.application.routes.draw do

  resources :profiles
  resources :tags, except: [:show] do
    get :autocomplete_tag_name, :on => :collection
  end

  get 'comments/comment_history'
  get 'questions/question_history'
  get 'answers/answer_history'

  resources :votes, :except => [:edit, :update, :show, :destroy] do
    collection do
      post 'upvote'
    end
  end

  concern :commentable do
    resources :comments
  end

  resources :questions, concerns: :commentable do
    collection do
      get 'tagged/:tag', to: 'tags#index', as: :tag
      get 'tagged/:tag/:user_id', to: 'tags#index', as: :user
      get :autocomplete_tag_name
      get :autocomplete_question_title
    end
    resources :answers, concerns: :commentable
  end
  get '/question/*id(/:title)' => 'questions#show', :as => :ques

  devise_for :users
  get '/user/*id(/:full_name)' => 'users#show', :as => :user

  root 'questions#index'

  mount Ckeditor::Engine => '/ckeditor'

end

app/models/question.rb
class Question < ActiveRecord::Base
  include Common
  belongs_to :user
  has_many :votes, as: :votable, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :answered_users, :source => :user, :through => :answers
  has_many :comments, as: :commentable
  has_many :histories, as: :historiable, dependent: :destroy
  validates :title, :presence => true
  validates_length_of :title, :minimum => 3, :maximum => 100, :allow_blank => false
  validate :question_box_validation
  acts_as_taggable_on :tags
  extend FriendlyId
  friendly_id :title, use: :slugged

  def to_param
    "#{id}/#{title}"
  end

  def answers_count
    a= self.answers.count
    if a<=1
      "#{a} Answer"
    else
      "#{a} Answers"
    end
  end

  def question_box_validation
    question_box_squish_method = ActionView::Base.full_sanitizer.sanitize(self.question_box).squish
    if question_box_squish_method.size > 500
      errors.add(:question_box, "is too long,maximum 100 characters only allowed")
    end
  end

  def save_history(params="")
    self.histories.new(description: self.question_box, title: params[:question][:title], tags: params[:question][:tag_list])
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :set_post, only: [:show, :append_question_vote, :edit, :update, :destroy]
  before_filter :require_permission, only: [:edit, :destroy]
  autocomplete :tag, :name, :class_name => 'ActsAsTaggableOn::Tag'
  autocomplete :question, :title

  def index
    @questions=Question.questions_list(params)
  end

  def show
  end

  def new
    @question= current_user.questions.new
    @modal_dialog = false
    if request.format == :json
      @modal_dialog = true
      render json: {html: render_to_string("/questions/_form", layout: false)} and return
    end
  end

  def edit
  end

  def create
    @question = current_user.questions.new(question_params)
    if @question.save
      redirect_to @question, notice: t(:question_create)
    else
      render :new
    end
  end

  def update
    if @question.question_box!= params[:question][:question_box]
      @question.save_history(params)
    end
    @question.update_attributes(question_params)

    if @question.save
      redirect_to questions_path, notice: t(:question_updated)
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to questions_url, notice: t(:question_destroy)
  end

  def question_history
    @question_history = Question.list_comment_history(params[:history_id])
  end

  private

  def set_post
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :question_box, :user_views, {:tag_list => []})
  end

  def answer_params
    if request.post?
      params.require(:answer).permit(:answer)
    end
  end



  def require_permission
    if current_user != @question.user
      redirect_to questions_path, notice: 'You are not allowed to edit this question'
    end
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
  def recent_question_update(question)
    question.question_box.capitalize.html_safe
  end

  def question_pagination
    param = params[:per_page]
    p param
    content_tag(:ul, class: ["pagination", "pagination"]) do
      if param == '5'
        li_tag(param)
      elsif param == '10'
        li_tag(param)
      elsif param == '20'
        li_tag(param)
      else
        li_tag
      end
    end
  end

  def li_tag(active="")
    links = ""
    links += "#{content_tag(:li, class: "#{active == '5' ? 'active' : ''}") do
        link_to(5, '/questions?per_page=5', :rel => 'next')
      end}"
    links += "#{content_tag(:li, class: "#{active == '10' ? 'active' : ''}") do
        link_to(10, '/questions?per_page=10', :rel => 'next')
      end}"
    links += "#{content_tag(:li, class: "#{active == '20' ? 'active' : ''}") do
        link_to(20, '/questions?per_page=20', :rel => 'next')
      end}"
    links += "#{content_tag(:li, class: "#{active == '30' ? 'active' : ''}") do
        link_to(30, '/questions?per_page=30', :rel => 'next')
      end}"
    links.html_safe
  end
  def create_tag(current_user)
    if current_user && current_user.is_admin
      link_to 'Tag', new_tag_path,class: "create-tag-button"
    end
  end
end

app/views/questions/_append_question_vote.html.haml
.question
  .pull-left
    %span= link_to_vote('upvote', '', question)
    %span= display_sum_of_votes(question)
    %span= link_to_vote('downvote', '', question)
  .pull-left
    %span= recent_question_update(question)
  .pull-left
    %span.fullname= "- #{question.user.full_name}"
  .clearfix
  %hr

app/views/questions/_form.html.haml
.col-lg-2
.col-lg-8
  = form_for(@question) do |f|
    - all_views_side_error_messages!(@question)
    .field
      = f.label :Title
      %br/
      = f.autocomplete_field :title, autocomplete_question_title_questions_path, class: "form-control"
    / %br/
    .field
      = f.label :Questions
      %br/
      = f.text_area :question_box, :placeholder => 'Enter your question', :class => @modal_dialog ? "ckeditor-2" : "ckeditor", :id => @modal_dialog ? "question_dialog_box" : "question_box", :rows => "8"
    .field
      = f.label :Tag
      %br/
      = f.select :tag_list, options_for_select(ActsAsTaggableOn::Tag.all.collect{|f| [f.name]}, :selected => f.object.tag_list),{},{prompt: "Enter your tag", class: "select-multiple form-control", multiple: 'multiple', include_blank: false}
    %br
    .actions
      = @question.id.present? ? (f.submit "Update question", :class => " btn btn-primary btn-xs") : (f.submit "Create question", :class => " btn btn-primary btn-xs")

.col-lg-2

app/views/questions/_question_history.html.haml
.col-sm-12.answer-comment
  - @question_history.each do |history|
    %span= history.description.html_safe
    %span.fullname= "- #{history.historiable.user.profile.full_name}"
    %br/
    %br/

app/views/questions/_trigger_question_vote.html.haml
.pull-left
  %span= link_to_vote('upvote', '', question)
  %span= display_sum_of_votes(question)
  %span= link_to_vote('downvote', '', question)
  %br
.col-sm-11.allignment_text
  %span.question= recent_question_update(question).html_safe
  .question-show-image
    = " Asked #{question.created_at.to_s(:short)} "
    - if question.user.profile.image.thumb.url.present?
      = image_tag(question.user.profile.image.thumb.url)
    - else
      = image_tag("download.png", width: "40px", height: "30px")
    %span= link_to "- #{question.user.profile.full_name_profile}",user_path(question.user, question.user.profile.full_name)
  - if question.user.present?
    - if current_user == question.user
      %span= link_to 'Edit | ', edit_question_path(question)
      - unless question.check_history?
        %span= link_to 'Edited | ', questions_question_history_path(history_id: question.id, dont_show: question.id), "data-target": "#myModal", "data-toggle": "modal", remote: true
      %span= link_to 'Destroy', question,method: :delete, data: { confirm: 'Are you sure?' }
.clearfix

app/views/questions/comment_edit.js.erb
$(".append_question_comment_<%= id %>").empty().append("<%= j render partial: '/comments/append_question_comment_vote', locals: {comment: @commentable, question: nil} %>");

app/views/questions/edit.html.haml
%h1 Editing Question
= render 'form'

app/views/questions/index.html.haml
.col-lg-0
.col-lg-8
  -if @questions.count >= 5
    - unless params[:tag]
      %span.pull-right= will_paginate @questions, renderer:  BootstrapPagination::Rails
      %span.pull-left= question_pagination
  %br
  %br
  %br
  %h3 Questions
  = link_to 'create question', new_question_path,class: "create-question-button"
  - @questions.each do |question|
    .align-count= display_sum_of_votes(question)
    = "Votes"
    %span.align-question-title= link_to question.title.humanize, ques_path(question)
    .align-question-description
      %span= truncate(question.question_box, length: 20, escape: false)
    .question-index-image
      = " Asked #{question.created_at.to_s(:short)} "
      - if question.user.profile.image.thumb.url.present?
        = image_tag(question.user.profile.image.thumb.url)
      - else
        = image_tag("download.png", width: "40px", height: "30px")
      %span.fullname= link_to "-#{question.user.profile.full_name_profile}", user_path(question.user, question.user.profile.full_name)
    .align-question-index
      .align-count= question.answers.size
      = "Answers"
    .question-list-tag
      - question.tags.each do |tag|
        = link_to tag, tag_questions_path(tag.name), class: "question-tag"
    .index-edit
      - if question.user.present?
        - if current_user == question.user
          %span= link_to 'Edit |', edit_question_path(question)
          - unless question.check_history?
            %span= link_to 'Edited |', questions_question_history_path(history_id: question.id, dont_show: question.id), "data-target": "#myModal", "data-toggle": "modal", remote: true
          %span= link_to 'Destroy', question,method: :delete, data: { confirm: 'Are you sure?' }
    %hr.hor-line

  -if @questions.count >= 5
    - unless params[:tag]
      %span= will_paginate @questions, renderer:  BootstrapPagination::Rails
      %span.pull-right= question_pagination
.col-lg-4

app/views/questions/new.html.haml
= render 'form'

app/views/questions/new.js.erb
$('.modal-dialog').addClass('modal-lg');
$('.modal-title').empty().append('Create Question');
$.fn.modal.Constructor.prototype.enforceFocus = function() {
  $('.modal-body').html("<%= j render partial: '/questions/form'%>")
};

app/views/questions/question_history.html.haml
.answer-comment
  - @question_history.each do |question|
    %span= question.question_box.html_safe
    %span.fullname= "- #{question.user.full_name}"
    %br/
    %br/

app/views/questions/question_history.js.erb
$('.modal-dialog').addClass('modal-lg');
$('.modal-title').empty().append('Edited Question');
$('.modal-body').html("<%= j render partial: '/questions/question_history'%>")

app/views/questions/show.html.haml
.show_error
.col-lg-0
.col-lg-8
  .question_title
    = @question.title.humanize
  .append_question
    = render partial: 'questions/trigger_question_vote', locals: {:question => @question}
    %hr.hor-line-ques
  .answer-comment.ques-cmt
    - @question.comments.each do |comment|
      = render partial: 'comments/append_question_comment_vote', locals: {comment: comment, question: @question}
  .create_comment
    - if current_user
      .hide-comment-button= link_to 'Add comment', "javascript:void();", class: " btn btn-primary btn-xs", id: "comment_#{@question.id}", url_id: "#{@question.id}"
      %div{:class => "append_create_comment_#{@question.id}"}
      %i.fa.fa-refresh.fa-spin.hide{:style => "font-size:24px"}
  %br/
  %div{:class => "ques_ans_page_#{@question.id}"}
    = render partial: "answers/index", locals: {answers: @answers, question: @question, comments: @comments, question_answers: @question.answers.order("created_at DESC").pages(params[:page])}
.col-lg-4

app/views/questions/show.js.erb
$('.fa-spin').removeClass('hide');
<% if @commentable.errors.size != 0 %>
  toastr.error("<%= all_views_side_error_messages!(@commentable)%>");
<% else %>
  $('.ques-cmt').append("<%= j render partial: '/comments/append_question_comment_vote', locals: {comment: @commentable, question: @question} %>");
  toastr.success('<%= t(:question_comment_create)%>');
  $('.hide-hr-line').removeClass("hide");
<% end %>
$('.fa-spin').addClass('hide');
$('.remove_new_comment').remove();
$('.hide-comment-button').removeClass("hide");

app/views/questions/user.html.haml
.form-group
          = f.label :firstname, :class => "col-sm-4 control-label"
          .col-sm-8
            = f.text_field :first_name, autofocus: true, :class => "form-control"
        .form-group
          = f.label :lastname, :class => "col-sm-4 control-label"
          .col-sm-8
            = f.text_field :last_name, autofocus: true, :class => "form-control"
            / .form-group
        /   = f.label :Add_Avatar, :class => "col-sm-4 control-label"
        /   = f.file_field :image, :class => "col-sm-8"
        / .form-group
        /   - if current_user.image.url.present?
        /     .col-sm-3
        /     .col-sm-5
        /       = f.check_box :remove_image
        /       = f.label :remove_avatar
        / - @user.build_profile
        / = f.fields_for :profile do |profile_fields|
        /   .form-group
        /     = profile_fields.label :Tag, :class => "col-sm-4 control-label"
        /     .col-sm-8
        /       = profile_fields.text_field :tag, autofocus: true, :class => "form-control"
        /   .form-group
        /     = profile_fields.label :Organization, :class => "col-sm-4 control-label"
        /     .col-sm-8
        /       = profile_fields.text_field :organization, autofocus: true, :class => "form-control"
        /   .form-group
        /     = profile_fields.label :Country, :class => "col-sm-4 control-label"
        /     .col-sm-8
        /       = profile_fields.select(:country, options_for_select(Country.show_country),{},{ class: "select-field form-control", "data-live-search": "true"})
        /   .form-group
        /     = profile_fields.label :State, :class => "col-sm-4 control-label"
        /     .col-sm-8
        /       = profile_fields.select(:state, options_for_select(State.show_state),{},{ class: "select-field form-control", "data-live-search": "true"})

        /   .form-group
        /     = profile_fields.label :City, :class => "col-sm-4 control-label"
        /     .col-sm-8
        /       = profile_fields.text_field :city, autofocus: true, :class => "form-control"
        /   .form-group
        /     = profile_fields.label :Description, :class => "col-sm-4 control-label"
        /     .col-sm-8
        /       = profile_fields.text_field :description, autofocus: true, :class => "form-control"
        /