config/routes.rb
Rails.application.routes.draw do

  resources :profiles
  resources :tags, except: [:show] do
    get :autocomplete_tag_name, :on => :collection
  end

  get 'comments/comment_history'
  get 'questions/question_history'
  get 'answers/answer_history'

  resources :votes, :except => [:edit, :update, :show, :destroy] do
    collection do
      post 'upvote'
    end
  end

  concern :commentable do
    resources :comments
  end

  resources :questions, concerns: :commentable do
    collection do
      get 'tagged/:tag', to: 'tags#index', as: :tag
      get 'tagged/:tag/:user_id', to: 'tags#index', as: :user
      get :autocomplete_tag_name
      get :autocomplete_question_title
    end
    resources :answers, concerns: :commentable
  end
  get '/question/*id(/:title)' => 'questions#show', :as => :ques

  devise_for :users
  get '/user/*id(/:full_name)' => 'users#show', :as => :user

  root 'questions#index'

  mount Ckeditor::Engine => '/ckeditor'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Common
  has_many :votes, as: :votable, dependent: :destroy
  belongs_to :commentable, polymorphic: true
  belongs_to :user
  has_many :histories, as: :historiable
  validates :comment, :presence => true



end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :find_question, only: [:create, :show, :edit, :new, :update, :destroy]

  def new
    commentable = find_commentable
    @commentable= commentable.comments.new
    render json: {html: render_to_string("/comments/_form", layout: false, locals: {question_id: @question, comment_id: @commentable})} and return
  end

  def index
    @comments=Comment.all
  end

  def destroy
    @commentable.destroy
    render :nothing => true
  end

  def update
    old_id = params[:id]
    if @commentable.comment != params[:comment][:comment]
      @commentable.histories.new(description: @commentable.comment)
      @commentable.update_attributes(comment_params)

    else
      @commentable.update_attributes(comment_params)
    end
    @commentable.save
    respond_to do |format|
      if(@commentable.commentable_type == "Question")
        format.js { render '/questions/comment_edit.js.erb',locals: {question: @question, comment: @commentable, id: old_id}}
      else

        format.js { render '/answers/answer_comment_edit.js.erb',locals: {question: @question, comment: @commentable, id: old_id}}
      end
    end
  end

  def create

    commentable = find_commentable
    @commentable = commentable.comments.new(comment_params)
    @commentable.user = current_user
    respond_to do |format|
      @commentable.save
      if(@commentable.commentable_type == "Question")
        # render js: {action: 'show', status: :created, location: commentable}
        format.html {redirect_to @question, notice: t(:question_comment_create), id: "question_comment"}
        # format.js { render action: 'append', status: :created, location: commentable }
        format.js { render '/questions/show.js.erb'}
      else
        format.html {redirect_to @question, notice: t(:answer_comment_create), id: "answer_comment"}
        format.js { render '/answers/show_comment.js.erb'}
      #   redirect_to @question, notice: t(:answer_comment_create)
      end
    end
  end

  def edit
    render json: {html: render_to_string("/comments/_form", layout: false, locals: {question_id: @question, comment_id: @commentable})} and return

  end


  def comment_history
    @comment_history = Comment.list_comment_history(params[:history_id])
  end

  private

  def comment_params
    params.require(:comment).permit(:comment)
  end

  def find_commentable
    if params[:question_id] && params[:answer_id]
      klass = "answers"
      id = params[:answer_id]
    else
      klass = "questions"
      id = params[:question_id]

    end
    return "#{klass}".singularize.classify.constantize.find(id)
  end

  def set_post
    @commentable = Comment.find(params[:id])
  end

  def find_question
    @question = Question.find(params[:question_id])
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
  # def comment_error_messages!
  #  return '' if @commentable.errors.empty?
  #  flash.now[:error] = @commentable.errors.full_messages.map { |msg| "#{msg}." }[0]
  # end
end

app/views/comments/_append_answer_comment_vote.html.haml
%div{class: "append_answer_comment_#{comment.id}"}
  = render partial: 'comments/trigger_answer_comment_vote', locals: {comment: comment, question: question, answer: answer}
  .col-sm-11.allignment_text_comment
    %span.comment-font= comment.comment.html_safe
    %span.fullname= "- #{comment.user.profile.full_name_profile}"
    - if current_user == comment.user
      %div{:class => "edit_answer_comment_#{comment.id}"}
        .pull-left
          %span.fullname= link_to 'Edit |',  "javascript:void();", id: "comment_#{comment.id}",url_comment_id: "#{comment.id}", url_id: "#{comment.commentable.id}", q_id: "#{question.id}"
      - unless comment.check_history?
        %span.fullname= link_to 'Edited |', comments_comment_history_path(history_id: comment.id, dont_show: comment.id),"data-target": "#myModal", "data-toggle": "modal", remote: true

      %span.fullname= link_to 'Destroy',  "javascript:void();", id: "destroy_#{comment.id}",destroy_id: "#{comment.id}", url_id: "#{comment.commentable.id}", q_id: "#{question.id}"
      %div{:class => "append_edit_answer_comment_#{comment.id}"}
    %hr

  .clearfix

app/views/comments/_append_question_comment_vote.html.haml
%div{class: "append_question_comment_#{comment.id}"}
  = render partial: 'comments/trigger_question_comment_vote', locals: {comment: comment, question: question}
  .col-sm-11.allignment_text_comment
    %span.comment-font= comment.comment.html_safe
    %span.fullname= "-#{comment.user.profile.full_name_profile}"
    - if current_user == comment.user
      %div{:class => "edit_comment_#{comment.id}"}
        .pull-left
          %span.fullname= link_to 'Edit | ',  "javascript:void();", id: "comment_#{comment.id}",url_comment_id: "#{comment.id}", url_id: "#{comment.commentable.id}"
      - unless comment.check_history?
        %span.fullname= link_to 'Edited |', comments_comment_history_path(history_id: comment.id, dont_show: comment.id),"data-target": "#myModal", "data-toggle": "modal", remote: true
      %span.fullname= link_to 'Destroy',  "javascript:void();", id: "destroy_#{comment.id}",destroy_id: "#{comment.id}", url_id: "#{comment.commentable.id}"
    %div{:class => "append_edit_comment_#{comment.id}"}
    %hr
  .clearfix

app/views/comments/_comment_history.html.haml
.answer-comment
  - @comment_history.each do |history|
    %span= history.description
    %span.fullname= "- #{history.historiable.user.profile.full_name}"
    %br/
    %br/

app/views/comments/_form.html.haml
.col-lg-0
.col-lg-8.remove_new_comment
  = form_for([@question, @commentable], remote: true) do |f|
    - all_views_side_error_messages!(@commentable)
    -p @commentable
    .field
      = f.label :Comment
      %br/
      = f.text_area :comment, :placeholder => 'Enter your comment', :class => 'form-control', :rows => "8"
      - if params[:answer_id].present?
        = hidden_field_tag :answer_id, params[:answer_id]
    %br
    .actions
      = @commentable.id.present? ? (f.submit "Update Comment", :class => " btn btn-primary btn-xs") : (f.submit "Create Comment", :class => " btn btn-primary btn-xs")
.col-lg-4
.clearfix

app/views/comments/_index.html.haml
.answer-comment
  - question.comments.each do |comment|
    - question_comment = comment
    %span= link_to_comment_vote( 'upvote', '', question, comment)
    %span= display_sum_of_votes(comment)
    %span= link_to_comment_vote('downvote', '', question, comment)
    %span= question_comment.comment.html_safe
    %span.fullname= "- #{question_comment.user.full_name}"
    - if current_user == question_comment.user
      %span.fullname= link_to 'Edit', edit_question_comment_path(path1(question_comment, question))
      - unless question_comment.check_history?
        %span.fullname= link_to 'Edited', comments_comment_history_path(history_id: question_comment.id, dont_show: question_comment.id)


      %span.fullname= link_to 'Destroy', question_comment_path(path1(question_comment, question)), method: :delete, data: { confirm: 'Are you sure?' }
    %br/
    %hr

app/views/comments/_trigger_answer_comment_vote.html.haml
.pull-left
  %div{class: "trigger_answer_comment_#{comment.id}"}
    %span= link_to_comment_vote( 'upvote','', question, comment, comment.commentable)
    %span= display_sum_of_votes(comment)
    %span= link_to_comment_vote( 'downvote','', question, comment, comment.commentable)

app/views/comments/_trigger_question_comment_vote.html.haml
.pull-left
  %div{class: "trigger_question_comment_#{comment.id}"}
    %span= link_to_comment_vote( 'upvote', '', comment.commentable, comment)
    %span= display_sum_of_votes(comment)
    %span= link_to_comment_vote('downvote', '', comment.commentable, comment)

app/views/comments/comment_history.html.haml
.answer-comment
  - @comment_history.each do |comment|
    %span= comment.comment
    %span.fullname= "- #{comment.user.full_name}"
    %br/
    %br/

app/views/comments/comment_history.js.erb
// $('.modal-dialog').addClass('modal-lg');
$('.modal-title').empty().append('Edited Comment');
$('.modal-body').html("<%= j render partial: '/comments/comment_history'%>")

app/views/comments/create.html.haml
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.haml
%h1 Editing Comment
= render 'form'

app/views/comments/new.html.haml
= render 'form'
/= link_to 'Back', questions_path

app/views/comments/update.html.haml
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>