config/routes.rb
Rails.application.routes.draw do

  resources :profiles
  resources :tags, except: [:show] do
    get :autocomplete_tag_name, :on => :collection
  end

  get 'comments/comment_history'
  get 'questions/question_history'
  get 'answers/answer_history'

  resources :votes, :except => [:edit, :update, :show, :destroy] do
    collection do
      post 'upvote'
    end
  end

  concern :commentable do
    resources :comments
  end

  resources :questions, concerns: :commentable do
    collection do
      get 'tagged/:tag', to: 'tags#index', as: :tag
      get 'tagged/:tag/:user_id', to: 'tags#index', as: :user
      get :autocomplete_tag_name
      get :autocomplete_question_title
    end
    resources :answers, concerns: :commentable
  end
  get '/question/*id(/:title)' => 'questions#show', :as => :ques

  devise_for :users
  get '/user/*id(/:full_name)' => 'users#show', :as => :user

  root 'questions#index'

  mount Ckeditor::Engine => '/ckeditor'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :questions
  has_many :answers
  has_many :answered_questions, :source => :question, :through => :answers
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments
  has_many :votes
  has_one :profile, dependent: :destroy
  accepts_nested_attributes_for :profile





end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]
  def show
  end
  def index
    @user=User.all
  end
  private

  def set_user
    @user = User.find(params[:id])
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.haml
%br
  %div
  %ul.nav.nav-tabs{:role => "tablist"}
    %span= link_to 'create question', new_question_path, class: "profile-question-button"
    = link_to 'All Questions', questions_path, class: "profile-question-all-button"
    %li.active{:role => "presentation"}
      %a{"aria-controls" => "profile", "data-toggle" => "tab", :href =>  "#profile", :role => "tab"} Profile
    %li{:role => "presentation"}
      %a{"aria-controls" => "activity", "data-toggle" => "tab", :href => "#activity", :role => "tab"} Activity
.tab-content
  #profile.tab-pane.active{:role => "tabpanel"}
    .col-lg-6
      - if @user.profile.image.medium.url.present?
        %br
        = image_tag(@user.profile.image.medium.url)
      - else
        %br
        = image_tag("download.png", width: "140px", height: "140px")
      .profile-name= @user.profile.full_name_profile
      .profile-description= @user.profile.description
    .col-lg-6
      .ques-count= @user.questions.size
      .ques-display= "questions"
      .ans-count= @user.answers.size
      .ans-display= "answers"
  #activity.tab-pane{:role => "tabpanel"}
    .col-lg-6
      %br
      .ques-profile-display
        %span= "Questions"
        %span= "(#{@user.questions.size})"
      %hr
      - @user.questions.each do |question|
        %span.align-vote-profile= display_sum_of_votes(question)
        - if (question.question_box.length >= 100)
          %span= link_to strip_tags(truncate(question.question_box, length: 50, escape: false)), question, class: "activity-question"
        - else
          %span= link_to strip_tags(question.question_box), question, class: "activity-question"
        %br
        %br
      .ques-profile-display
        %span= "Voted Questions"
        %span= "(#{@user.votes.includes(:votable).where(votable_type: "Question").size})"
      %hr
      - @user.votes.includes(:votable).where(votable_type: "Question").each do |vote|
        %span.align-vote-profile= display_sum_of_votes(vote.votable)
        - if (vote.votable.question_box.length >= 100)
          %span= link_to strip_tags(truncate(vote.votable.question_box, length: 50, escape: false)), vote.votable, class: "activity-question"
        - else
          %span= link_to strip_tags(vote.votable.question_box), vote.votable, class: "activity-question"
        %br
        %br
      .ques-profile-display
        %span= "Comments"
        %span= "(#{@user.comments.includes(:commentable).size})"
      %hr
      - @user.comments.includes(:commentable).each do |c|
        %span.align-vote-profile= display_sum_of_votes(c.commentable_type == "Question" ? c.commentable : c.commentable.question)
        %span= link_to strip_tags(c.comment), c.commentable_type == "Question" ? c.commentable : c.commentable.question, class: "activity-question"
        %br
        %br
    .col-lg-6
      %br
      .ques-profile-display
        %span= "Answers"
        %span= "(#{@user.answers.size})"
      %hr
      - @user.answers.includes(:question).each do |answer|
        %span.align-vote-profile= display_sum_of_votes(answer)
        - if (answer.answer.length >= 100)
          %span= link_to truncate(answer.answer.html_safe, length: 50, escape: false), answer.question, class: "activity-question"
        -else
          %span= link_to answer.answer.html_safe, answer.question, class: "activity-question"
        %br
        %br
      .ques-profile-display
        %span= "Voted Answers"
        %span= "(#{@user.votes.includes(:votable).where(votable_type: "Answer").size})"
      %hr
      - @user.votes.includes(:votable).where(votable_type: "Answer").each do |vote|
        %span.align-vote-profile= display_sum_of_votes(vote.votable)
        - if (vote.votable.answer.length >= 100)
          %span= link_to truncate(vote.votable.answer.html_safe, length: 30, escape: false), vote.votable.question, class: "activity-question"
        - else
          %span= link_to vote.votable.answer.html_safe, vote.votable.question, class: "activity-question"
        %br
        %br
      .ques-profile-display
        = "Tags"
      %hr
      - @user.questions.includes(:tags).each do |f|
        - f.tags.each do |n|
          %span.question-tag=link_to n.name,user_questions_path(n.name, @user), class: "activity-tag"
          %br
          %br