config/routes.rb
Rails.application.routes.draw do

  resources :profiles
  resources :tags, except: [:show] do
    get :autocomplete_tag_name, :on => :collection
  end

  get 'comments/comment_history'
  get 'questions/question_history'
  get 'answers/answer_history'

  resources :votes, :except => [:edit, :update, :show, :destroy] do
    collection do
      post 'upvote'
    end
  end

  concern :commentable do
    resources :comments
  end

  resources :questions, concerns: :commentable do
    collection do
      get 'tagged/:tag', to: 'tags#index', as: :tag
      get 'tagged/:tag/:user_id', to: 'tags#index', as: :user
      get :autocomplete_tag_name
      get :autocomplete_question_title
    end
    resources :answers, concerns: :commentable
  end
  get '/question/*id(/:title)' => 'questions#show', :as => :ques

  devise_for :users
  get '/user/*id(/:full_name)' => 'users#show', :as => :user

  root 'questions#index'

  mount Ckeditor::Engine => '/ckeditor'

end

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
      %meta{:content => "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}
        %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
          %title= content_for?(:title) ? yield(:title) : "Explosion"
          = csrf_meta_tags
          = stylesheet_link_tag "application", :media => "all"
          / For third-generation iPad with high-resolution Retina display:
          / Size should be 144 x 144 pixels
          = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
          / For iPhone with high-resolution Retina display:
          / Size should be 114 x 114 pixels
          = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
          / For first- and second-generation iPad:
          / Size should be 72 x 72 pixels
          = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
          / For non-Retina iPhone, iPod Touch, and Android 2.1+ devices:
          / Size should be 57 x 57 pixels
          = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
          / For all other devices
          / Size should be 32 x 32 pixels
          = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
          = javascript_include_tag "application"
          / Le HTML5 shim, for IE6-8 support of HTML elements
          /[if lt IE 9]
            <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
  %body
    .wrapper
      %nav.navbar.navbar-default
        .container
          / Brand and toggle get grouped for better mobile display
          .navbar-header
            %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
              %span.sr-only Toggle navigation
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            %a.navbar-brand{ :href => root_path }Explosion

          #bs-example-navbar-collapse-1.collapse.navbar-collapse
            %ul.nav.navbar-nav
              %li.dropdown
                %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}

                  Questions
                  %span.caret
                %ul.dropdown-menu
                  -if current_user
                    %li
                      = link_to "Create Question", "javascript:void()", id: :new_question_create#, remote: true
                  %li
                    = link_to "All Questions",root_path
            - if current_user && current_user.is_admin
              %ul.nav.navbar-nav
                %li.dropdown
                  %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}

                    Administration
                    %span.caret
                  %ul.dropdown-menu
                    %li
                      = link_to 'Tag', new_tag_path



            %ul.nav.navbar-nav.navbar-right{class: user_signed_in? ? "signed-in-navbar" : ""}

              - unless user_signed_in?
                %li
                  %a.navbar-brand{ :href => new_user_session_path }Sign in
                  / = link_to "Sign in",new_user_session_path
                %li
                  %a.navbar-brand{ :href => new_user_registration_path }Sign up
                  / = link_to "Sign up",new_user_registration_path
              -else
                %li.dropdown
                  %a.dropdown-toggle{"aria-expanded" => "true", "aria-haspopup" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                    = image_tag(current_user.profile.image.thumb.url)
                    = current_user.profile.full_name_profile
                    %span.caret
                  %ul.dropdown-menu
                    %li
                      = link_to "Account Update",edit_user_registration_path
                    %li.divider{:role => "separator"}
                    %li

                      = link_to "Edit Profile",edit_profile_path(current_user.profile)
                    %li.divider{:role => "separator"}

                    %li
                      = link_to "Sign Out",destroy_user_session_path,method: :delete



      .container
        .row
          = bootstrap_flash
          = yield
          #myModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
            .modal-dialog
              .modal-content
                .modal-header
                  %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} &times;
                  %h4.modal-title
                .modal-body
                .modal-footer
                  %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close
                  / %button.btn.btn-primary{:type => "button"} Save changes

      .push
  %footer
    .container
      %p.text-muted @copyright #{Time.now.year} explosion social page
    / /container